### ISSUE TITLE
src/host/os_getnumcpus.c:59:11: error: use of undeclared identifier 'HW_AVAILCPU' on FreeBSD

### ISSUE THREAD

**Issue by Martinfx** [premake/premake-core#2328]
**What seems to be the problem?**
Hi,
i tried compile beta3 version premake and i have problem with HW_AVAILCPU flag

FreeBSD 14.1-RELEASE

**What did you expect to happen?**
```
===>  License BSD3CLAUSE accepted by the user
===>   premake5-5.0.0.b3 depends on file: /usr/local/sbin/pkg - found
===> Fetching all distfiles required by premake5-5.0.0.b3 for building
===>  Extracting for premake5-5.0.0.b3
=> SHA256 Checksum OK for premake-5.0.0-beta3-src.zip.
===>  Patching for premake5-5.0.0.b3
===>   Converting DOS text files to UNIX text files
===>  Applying FreeBSD patches for premake5-5.0.0.b3 from /usr/ports/devel/premake5/files
===>   premake5-5.0.0.b3 depends on package: gmake>=4.4.1 - found
===>  Configuring for premake5-5.0.0.b3
===>  Building for premake5-5.0.0.b3
rm -rf ./bin
rm -rf ./build
rm -rf ./obj
mkdir -p build/bootstrap
cc -o build/bootstrap/premake_bootstrap -DPREMAKE_NO_BUILTIN_SCRIPTS -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I"contrib/lua/src" -I"contrib/luashim" src/host/*.c contrib/lua/src/lapi.c contrib/lua/src/lbaselib.c contrib/lua/src/lbitlib.c contrib/lua/src/lcode.c contrib/lua/src/lcorolib.c contrib/lua/src/lctype.c contrib/lua/src/ldblib.c contrib/lua/src/ldebug.c contrib/lua/src/ldo.c contrib/lua/src/ldump.c contrib/lua/src/lfunc.c contrib/lua/src/lgc.c contrib/lua/src/linit.c contrib/lua/src/liolib.c contrib/lua/src/llex.c contrib/lua/src/lmathlib.c contrib/lua/src/lmem.c contrib/lua/src/loadlib.c contrib/lua/src/lobject.c contrib/lua/src/lopcodes.c contrib/lua/src/loslib.c contrib/lua/src/lparser.c contrib/lua/src/lstate.c contrib/lua/src/lstring.c contrib/lua/src/lstrlib.c contrib/lua/src/ltable.c contrib/lua/src/ltablib.c contrib/lua/src/ltm.c contrib/lua/src/lundump.c contrib/lua/src/lutf8lib.c contrib/lua/src/lvm.c contrib/lua/src/lzio.c  -lm
src/host/os_getnumcpus.c:59:11: error: use of undeclared identifier 'HW_AVAILCPU'
   59 |         mib[1] = HW_AVAILCPU;  // alternatively, try HW_NCPU;
      |                  ^
```
**What have you tried so far?**
 I looked to FreeBSD man page and this flag not exist

**How can we reproduce this?**
1. cd /usr/port/devel/premake5
2. change version to beta3 and then "make makesum"
3. make

- [ ] Visual Studio 2022 (vs2022)
- [ ] Visual Studio 2019 (vs2019)
- [ ] Visual Studio 2017 (vs2017)
- [ ] Visual Studio 2015 (vs2015)
- [ ] Visual Studio 2012 (vs2012)
- [ ] Visual Studio 2010 (vs2010)
- [ ] Visual Studio 2008 (vs2008)
- [ ] Visual Studio 2005 (vs2005)
- [ ] GNU Makefile (gmake)
- [ ] GNU Makefile 2 (gmake2)
- [ ] XCode (xcode)
- [ ] Codelite
- [ x] Other (Please list below)

**Comment by Jarod42** [comment]
Introduced by PR https://github.com/premake/premake-core/pull/2241
@tritao
